pluginManagement {
    includeBuild("build-logic")
    repositories {
        gradlePluginPortal()
        google()
    }
}

plugins {
    id("com.gradle.develocity") version "3.19.2"
}

// https://docs.gradle.com/enterprise/gradle-plugin/#controlling_when_build_scans_are_published
develocity {
    buildScan {
        uploadInBackground = false
        publishing.onlyIf { false }
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
        termsOfUseAgree = "yes"
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name = "MpeixGitHubPackages"
            url = uri("https://maven.pkg.github.com/tonykolomeytsev/mpeiapp")
            // readonly access token
            credentials {
                username = "tonykolomeytsev"
                password = new String("Z2l0aHViX3BhdF8xMUFFT0U2RlEwaEZRRnJSV0xtQ1R6XzdETjZ3bGJFWVlV".decodeBase64()) +
                        new String("MWR6QXFqRXFGcUFLTVFjaTl1NXR2YkRFbW00Q0VYMWJDVzRTTUFXWG95NXVrRmRD".decodeBase64())
            }
        }
    }
    versionCatalogs.create("mpeix").from(files("gradle/mpeix.versions.toml"))
}

rootProject.name = "mpeix"

// Automatically add all project modules
def sourcesDir = layout.rootDirectory.dir("modules").asFile
fileTree(sourcesDir) {
    exclude("**/build/**", "**/src/**", "build-logic", ".*")
    include("*/**/build.gradle")
}.forEach { buildScriptFile ->
    def moduleDir = buildScriptFile.parentFile
    // do NOT use absolute paths, or Gradle will shit himself
    def relativePath = sourcesDir.toPath().relativize(moduleDir.toPath())
    def moduleName = ":$relativePath".replace(File.separator, "_")

    include(moduleName)
    project(moduleName).projectDir = moduleDir
}


