[illustrations]
ill_bars = "Onboarding / Bars"
ill_notes = "Onboarding / Notes"
ill_schedule = "Onboarding / Schedule"

# raster images inside
ill_map = { name = "Onboarding / Map", quality = 75 }
gradient_logo = { name = "Onboarding / Logo", quality = 80 }
