[versions]

# mpeix application version
appVersionName = "2.0.0"
appVersionCode = "44"

agp = "7.2.1" # android gradle plugin
minSdk = "21"
targetSdk = "32"
buildTools = "33.0.0"
kotlin = "1.7.0"

# AndroidX Versions
appCompat = "1.1.0"
recyclerView = "1.2.1"
constraintLayout = "2.1.0"
coordinatorLayout = "1.1.0"
viewPager2 = "1.0.0"
cardView = "1.0.0"
swipeRefreshLayout = "1.1.0"
fragmentKtx = "1.3.6"

# Google Versions
material = "1.4.0"

# Koin Versions
koin = "3.1.2"

# Squareup Versions
retrofit = "2.9.0"
okhttp = "4.9.0"

# Vivid Money Versions
elmslie = "1.1.4"

[libraries]
# Single Libraries
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
picasso = { module = "com.squareup.picasso:picasso", version = "2.8" }
coil = { module = "io.coil-kt:coil", version = "1.3.2" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version = "0.5.0" }

# AndroidX Libraries
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-coordinatorLayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayout" }
androidx-viewPager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewPager2" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "cardView" }
androidx-swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version = "1.3.2" }
androidx-lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version = "2.3.1" }
androidx-lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }

# Google Libraries
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version = "2.8.8" }
google-maps = { module = "com.google.android.gms:play-services-maps", version = "17.0.1" }

# Koin Libraries
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# Firebase Libraries
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "19.0.1" }
firebase-config = { module = "com.google.firebase:firebase-config", version = "21.0.1" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "18.2.1" }

# RxJava Libraries
rx-java = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.1" }
rx-android = { module = "io.reactivex.rxjava3:rxandroid", version = "3.0.0" }

# Squareup Libraries
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-rxJava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
squareup-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Vivid Money Libraries
vivid-elmslie-core = { module = "com.github.vivid-money.elmslie:elmslie-core", version.ref = "elmslie" }
vivid-elmslie-android = { module = "com.github.vivid-money.elmslie:elmslie-android", version.ref = "elmslie" }
vivid-elmslie-storeHolder = { module = "com.github.vivid-money.elmslie:elmslie-store-persisting", version.ref = "elmslie" }

# Kotest Libraries
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version = "4.4.1" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version = "4.4.1" }
kotest-property = { module = "io.kotest:kotest-property", version = "4.4.2" }
