[versions]

agp = "8.10.1" # android gradle plugin
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"
coroutines = "1.10.2"
detekt = "1.23.8"

# AndroidX Versions
appCompat = "1.7.1"
recyclerView = "1.4.0"
constraintLayout = "2.2.1"
coordinatorLayout = "1.3.0"
viewPager2 = "1.1.0"
cardView = "1.0.0"
swipeRefreshLayout = "1.1.0"
fragment = "1.8.9"
room = "2.7.2"

# Google Versions
material = "1.12.0"

# Koin Versions
koin = "4.1.1"

# Squareup Versions
retrofit = "3.0.0"
okhttp = "5.1.0"

# Vivid Money Versions
elmslie = "3.0.0"

# Jetpack Compose Versions
accompanist = "0.23.1"
composeBom = "2025.08.00"

# MockServer
ktor = "2.3.0"

[libraries]

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Single Libraries
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
picasso = { module = "com.squareup.picasso:picasso", version = "2.8" }
coil = { module = "io.coil-kt:coil", version = "2.7.0" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version = "0.5.0" }
tinkoff-pagerIndicator = { module = "ru.tinkoff.scrollingpagerindicator:scrollingpagerindicator", version = "1.2.1" }

# AndroidX Libraries
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-coordinatorLayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayout" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version = "1.16.0" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version = "2.9.3" }
androidx-lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-rx3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version = "2.5.2" }
androidx-swipeRefreshLayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefreshLayout" }
androidx-viewPager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewPager2" }
androidx-datastore-prefs = { module = "androidx.datastore:datastore-preferences", version = "1.1.7" }

# Google Libraries
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version = "2.13.1" }
google-maps = { module = "com.google.android.gms:play-services-maps", version = "19.2.0" }

# Koin Libraries
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

# Firebase Libraries
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "19.0.1" }
firebase-config = { module = "com.google.firebase:firebase-config", version = "21.0.1" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "18.2.1" }

# RxJava Libraries
rx-java = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.11" }
rx-android = { module = "io.reactivex.rxjava3:rxandroid", version = "3.0.2" }

# Squareup Libraries
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-rxJava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
squareup-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
squareup-okhttp-logger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
chucker-impl = { module = "com.github.chuckerteam.chucker:library", version = "4.2.0" }

# Vivid Money Libraries
vivid-elmslie-core = { module = "money.vivid.elmslie:elmslie-core", version.ref = "elmslie" }
vivid-elmslie-android = { module = "money.vivid.elmslie:elmslie-android", version.ref = "elmslie" }

# Kotest Libraries
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version = "5.6.1" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version = "5.6.1" }
kotest-property = { module = "io.kotest:kotest-property", version = "5.6.1" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }

# Jetpack Compose
## Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
## Accompanist
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = "com.google.firebase.crashlytics:3.0.6"
google-services = "com.google.gms.google-services:4.4.3"
gradle-android-cacheFix = "org.gradle.android.cache-fix:3.0.1"

[bundles]

compose = [
    "compose-runtime",
    "compose-ui",
    "compose-ui-util",
    "compose-animation",
    "compose-foundation",
]

accompanist = [
    "accompanist-insets",
    "accompanist-insets-ui",
    "accompanist-permissions",
    "accompanist-systemUiController",
    "accompanist-swipeRefresh",
    "accompanist-pager",
]
