name: Android Debug Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: false

      # The Google Services Plugin cannot function without it
      - name: Materialize google services
        run: .ci/materialize.sh $GOOGLE_SERVICES_DEBUG modules/app/google-services.json
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}

      - name: Unit tests
        run: |
          ./gradlew -Pci test
        env:
          MAP_KEY: ${{ secrets.MAP_KEY }}

  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: false

      # The Google Services Plugin cannot function without it
      - name: Materialize google services
        run: .ci/materialize.sh $GOOGLE_SERVICES_DEBUG modules/app/google-services.json
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}

      - name: Build with Gradle
        run: ./gradlew -Pci :app:assembleDebug
        env:
          MAP_KEY: ${{ secrets.MAP_KEY }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: App Debug
          path: modules/app/build/outputs/apk/debug/app-debug.apk
