name: Android

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: "-Dorg.gradle.unsafe.configuration-cache=false"

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # The Google Services Plugin cannot function without it
      - name: Materialize google services
        run: .github/materialize.sh $GOOGLE_SERVICES_DEBUG modules/app/google-services.json
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
        env:
          MAP_KEY: ${{ secrets.MAP_KEY }}
