name: Pull Request

on:
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.unsafe.configuration-cache=false"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # The Google Services Plugin cannot function without it
      - name: Materialize google services
        run: .github/materialize.sh $GOOGLE_SERVICES_DEBUG modules/app/google-services.json
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}

      - name: Unit tests
        run: ./gradlew test
        env:
          MAP_KEY: ${{ secrets.MAP_KEY }}

  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # The Google Services Plugin cannot function without it
      - name: Materialize google services
        run: .github/materialize.sh $GOOGLE_SERVICES_DEBUG modules/app/google-services.json
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
        env:
          MAP_KEY: ${{ secrets.MAP_KEY }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: App Debug
          path: modules/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
