on:
  push:
    paths:
      - 'statics/map/README.md'
      - 'statics/map/markers_gen.py'
      - '.github/workflows/map-gen.yaml'

jobs:
  map-gen:
    name: Generate new map markers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run python generator script
        run: |
          cd statics/map
          python3 markers_gen.py

      - name: Push new markers to current branch
        run: |
          cd statics/map
          git config --global user.name "Anton Kolomeytsev"
          git config --global user.email "tonykolomeytsev@gmail.com"
          git add markers.json

      - name: Create pull request
          uses: peter-evans/create-pull-request@v4
          with:
            commit-message: Update map markers.json
            branch: map-gen/update-
            branch-suffix: short-commit-hash
            title: Update map markers.json
            